CryptoFinder/Models/ErrorViewModel.cs
using System;

namespace CryptoFinder.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CryptoFinder/Models/EthereumBlock.cs
using System;
using System.Collections.Generic;

namespace CryptoFinder.Models
{
    public class EthereumBlock
    {
        public string BaseFeePerGas { get; set; }
        public string difficulty { get; set; }
        public string extraData { get; set; }
        public string gasLimit { get; set; }
        public string gasUsed { get; set; }
        public string hash { get; set; }
        public string logsBloom { get; set; }
        public string miner { get; set; }
        public string mixHash { get; set; }
        public string nonce { get; set; }
        public string number { get; set; }
        public string parentHash { get; set; }
        public string receiptsRoot { get; set; }
        public string sha3Uncles { get; set; }
        public string size { get; set; }
        public string stateRoot { get; set; }
        public string timestamp { get; set; }
        public string totalDifficulty { get; set; }
        public List<EthereumTransaction> Transactions { get; set; }
    }
}

CryptoFinder/Models/EthereumError.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CryptoFinder.Models
{
    public class EthereumError
    {
        public int Code { get; set; }
        public string Message { get; set; }
    }
}

CryptoFinder/Models/EthereumRequest.cs
using System;
using System.Collections.Generic;

namespace CryptoFinder.Models
{
    public class EthereumRequest
    {
        public string Jsonrpc { get; set; }
        public int Id { get; set; }
        public string Method { get; set; }
        public List<Object> Params { get; set; }

        public EthereumRequest(string methodName, List<Object> parameters)
        {
            this.Jsonrpc = "2.0";
            this.Id = 1;
            this.Method = methodName;
            this.Params = parameters;
        }
    }
}

CryptoFinder/Models/EthereumResponse.cs
using Newtonsoft.Json;

namespace CryptoFinder.Models
{
    public class EthereumResponse
    {
        public string Jsonrpc { get; set; }
        public int Id { get; set; }
        public EthereumBlock Result { get; set; }
        public EthereumError Error { get; set; }
    }
}

CryptoFinder/Models/EthereumTransaction.cs
namespace CryptoFinder.Models
{
    public class EthereumTransaction
    {
        public string BlockHash { get; set; }
        public string BlockNumber { get; set; }
        public string Gas { get; set; }
        public string Hash { get; set; }
        public string From { get; set; }
        public string To { get; set; }
        public string Value { get; set; }
    }
}

CryptoFinder/Models/EthereumTransactionList.cs
using System.Collections.Generic;

namespace CryptoFinder.Models
{
    public class EthereumTransactionList
    {
        public IEnumerable<EthereumTransaction> Transactions { get; set; }
    }
}

CryptoFinder/Models/RequestParams.cs
using System;
using System.Collections.Generic;


namespace CryptoFinder.Models
{
    public class RequestParams
    {
        public List<Object> Params { get; set; }
    }
}

CryptoFinder/Models/Response.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CryptoFinder.Models
{
    public enum Status
    {
        SUCCESS,
        FAIL
    }

    public class Error
    {
        public Error()
        {
            this.Code = 0;
            this.Message = string.Empty;
            this.Description = string.Empty;
        }
        public int Code { get; set; }
        public string Message { get; set; }
        public string Description { get; set; }
    }

    public class Response<T>
    {
        public Response(Status status, T data)
        {
            this.Status = status;
            this.Data = data;
        }
        public Status Status { get; set; }
        public T Data { get; set; }
        
        public Error Error { get; set; }
    }
}

CryptoFinder/Controllers/EthereumController.cs
using CryptoFinder.Models;
using Etherium.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System;
using System.Net.Http;
using System.Threading.Tasks;

namespace Etherium.Controllers
{
    [Controller]
    public class EthereumController : Controller
    {
        private readonly IEthereumService ethereumService;

        public EthereumController(IEthereumService ethereumService)
        {
            this.ethereumService = ethereumService;
        }

        /// <summary>
        /// Search for transactions associated with an address within Ethereum block
        /// </summary>
        /// <param name="blockNumber"></param>
        /// <param name="address"></param>
        /// <returns></returns>
        [HttpGet("/searchTransactions")]
        public async Task<IActionResult> SearchTransactions(string blockNumber, string address)
        {
            //Validate input and return error if invalid
            if (string.IsNullOrEmpty(blockNumber) || string.IsNullOrEmpty(address))
            {
                return View("SearchTransactionsError", new Error() { Description = "BlockNumber/Adress input fields must have a value" });
            }

            //Get trasnactions from ethereum service
            var response = await this.ethereumService.SearchTransactions(blockNumber, address);
            if (response.Status == Status.SUCCESS)
            {
                //on success display search trasnaction page
                return View(response.Data);
            }
            else
                //on error display error page.
                return View("SearchTransactionsError", response.Error);
        }
    }
}

CryptoFinder/Controllers/HomeController.cs
using CryptoFinder.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

using System.Diagnostics;


namespace CryptoFinder.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CryptoFinder/Views/Ethereum/SearchTransactions.cshtml
@model EthereumTransactionList;
@{
    ViewData["Title"] = "SearchTransactions";

}

<style>
    table {
        width: 1200px;
        table-layout: fixed;
    }
    td {
        word-wrap: break-word
    }
</style>

<h2>Ethereum Transactions</h2>
<br /><br /><br />

<table class='table table-bordered header-fixed'>
    <thead class="thead-light">
        <tr>
            <th>Block Hash</th>
            <th>Block Number</th>
            <th>Gas</th>
            <th>Hash</th>
            <th>From</th>
            <th>To</th>
            <th>Value</th>
        </tr>
    </thead>

    @foreach (var item in Model.Transactions)
    {
        <tr>
            <td>@Html.DisplayFor(modelItem => item.BlockHash)</td>
            <td>@Html.DisplayFor(modelItem => item.BlockNumber)</td>
            <td>@Html.DisplayFor(modelItem => item.Gas)</td>
            <td>@Html.DisplayFor(modelItem => item.Hash)</td>
            <td>@Html.DisplayFor(modelItem => item.From)</td>
            <td>@Html.DisplayFor(modelItem => item.To)</td>
            <td>@Html.DisplayFor(modelItem => item.Value)</td>
        </tr>
    }
</table>

<br />
<button class="btn btn-secondary btn-sm" type="button" onclick="location.href='@Url.Action("Index", "Home")'">Search Again</button>

CryptoFinder/Views/Ethereum/SearchTransactionsError.cshtml
@model Error;
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div>
    <h2>Error searching for ethereum transactions</h2>
</div>
<br />
<br />
<br />

<div>
    <h5>Error description:</h5>
    <textarea rows="5" cols="80" wrap="hard" disabled>@Model.Description</textarea><br>
</div>

<button class="btn btn-secondary btn-sm" type="button" onclick="location.href='@Url.Action("Index", "Home")'">Search Again</button>

CryptoFinder/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<style>
    td {
        padding: 15px;
    }

    input {
        width: 500px
    }
</style>

<div>
    <h1>Search Ethereum Transactions</h1>
    <br /><br /><br />

    <form asp-controller="Ethereum" asp-action="searchTransactions" method="get">
        <table>
            <tr>
                <td>
                    <span><lable asp-for="blockNumber">Block Number</lable></span>
                </td>
                <td>
                    <input type="text" name="blockNumber" value="0xced189" />
                </td>
            </tr>
            <tr>
                <td>
                    <lable asp-for="address">Address</lable>
                </td>
                <td>
                    <input type="text" value="0x5aa3393e361c2eb342408559309b3e873cd876d6" name="address" />
                </td>
            </tr>
            <tr>
                <td>
                </td>
                <td>
                    <button type="submit">Search</button>
                </td>
            </tr>

        </table>

    </form>
</div>

CryptoFinder/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CryptoFinder</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CryptoFinder</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - CryptoFinder - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>